spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-keycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: spring-keycloak-api
      principle-attribute: preferred_username

##TODO DUMMY USER change me and store me in a vault
admin:
  username: vaxen
  password: admin
