spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081
jwt:
  auth:
    converter:
      resource-id: spring-keycloak-api
      principle-attribute: preferred_username

keycloak:
  host: http://localhost:8080
  realm: spring-keycloak
  client-id: spring-keycloak-api
  ##TODO DUMMY USER change me and store me in a vault
  admin:
    username: vaxen
    password: admin




